### ISSUE TITLE
Fit Test: Manta E3 EZ

### ISSUE THREAD

**Issue by jon-harper** [jon-harper/OmniBox#135]

**Comment by Paul-Damian** [comment]
I can confirm that the Manta E3EZ fits flawless to the tray :-)

![IMG_20240913_182725](https://github.com/user-attachments/assets/c3c07cdf-186f-4caf-99d0-19bc8cc1ac4b)

![IMG_20240913_184147](https://github.com/user-attachments/assets/4daadbfd-3185-46ad-8b5b-d653cf373f69)

**Comment by jon-harper** [comment]
Thanks much!
