### ISSUE TITLE
[Request] Inovato Quadra T95 Mini CPU

### ISSUE THREAD

**Issue by theweeirish** [jon-harper/OmniBox#138]
Im looking if it is possible for a tray for the Inovato Quadra t95 mini board to be mounted inside. 

https://www.alibaba.com/product-detail/New-Upgrade-T95-Mini-Android-9_1600134469365.html?mark=google_shopping&seo=1

Its an alt for using a pi, I can also modify an existing tray if provided. 

Thanks.

**Comment by jon-harper** [comment]
I apologize for the delay in replying here. That will fit on a long lower bay tray (or two). Look at the lower bay tray template as your most likely option here. I won't be able to make this myself, so I'm closing this issue.

If you have any other questions, drop on by Discord for a faster response. :-)
