### ISSUE TITLE
Add tray support for Solid State Relay

### ISSUE THREAD

**Issue by kameron-m7** [jon-harper/OmniBox#19]
Feature Request: Add support for Fotek SSR-40 DA relay

[https://www.amazon.com/SSR-40DA-Solid-Output-24-380V-SSR-40/dp/B07FVHWN82](Amazon)
[https://grabcad.com/library/ssr-40-da-1](GrabCAD)
[https://cdn.sparkfun.com/datasheets/Components/General/SSR40DA.pdf](TechSpecs).

Thanks!

**Comment by jon-harper** [comment]
Let me know how it fits and any suggestions you may have. I'm unsure if the slots that support the sides of the SSR are adequate to keep it from rocking.

**Comment by jon-harper** [comment]
I revisited the dimensions and realized I *can* fit it on a half tray! The latest commit should do it.

**Comment by kameron-m7** [comment]
Awesome, Thanks!

**Comment by jon-harper** [comment]
Heya @kameron-m7, how does it fit? I want to make sure all is well before I close the issue. 😃

**Comment by kameron-m7** [comment]
Fits well for me. Thanks!

**Comment by jon-harper** [comment]
Awesome!
