### ISSUE TITLE
Cram 2x Generic LM2596 onto half length tray

### ISSUE THREAD

**Issue by kameron-m7** [jon-harper/OmniBox#20]
Is this possible? I am running out of space in my box. Thanks.

**Comment by jon-harper** [comment]
You've got the two LM2596s, the SSR, and what else? I'll see what I can do, possibly adding a buck mount to the SSR tray.

**Comment by kameron-m7** [comment]
Mosfet, and that's it for that part of the box.

**Comment by jon-harper** [comment]
But the answer to your original question is yes, they will fit. 🙂
