### ISSUE TITLE
BIGTREETECH PITFT support?

### ISSUE THREAD

**Issue by Majawat** [jon-harper/OmniBox#3]
Love this project!

Any way you could add support for the BIGTREETECH PITFT screens? Either the 4.3", 5", or 7" (but 5" or 7" preferred).

https://www.biqu.equipment/collections/lcd/products/bigtreetech-pi-tft43-v2-0-screen-board?variant=39840251936866.

Not sure if you'd keep the PI mounted to the screen, or keep it in the tray (probably tray? though that'd require a longer DSI cable, which should be fine.)

**Comment by jon-harper** [comment]
Steve's original project has a set of 5" files that are easily adaptable and set the TFT on the lid above the display. I don't have access to a PITFT myself, but if you're willing to fit test, I'm willing to make the adjustments for you.

I'll also take a look at the 7" and see what I can do with that. Bear in mind the case is 7" wide, so it may look slightly awkward.

**Comment by jon-harper** [comment]
I've got CAD files for the display and Steve's mounts as reference. It looks like both the 5" and 7" will mount fine. The longer DSI cable is going to be necessary, btw.

I should have something for you to test before end of week. Which display are you getting, or do you have one already?

**Comment by jon-harper** [comment]
Do what's best for you, dude. If you want the 7", someone else will come along to test the 5". 🙂

**Comment by Majawat** [comment]
Haha, I definitely get what you're saying, just a hard decision for me. Ok, I'm going to go with the 5".

**Comment by jon-harper** [comment]
Heya, Majawat. Hope you're well. I'm almost done with some bugfixes and such to get 0.9.7 out the door. Getting your Pi TFT going is next on my design list.

The simplest approach is to attach a hollow pillar to the Raspberry Pi screw holes in the back of the TFT. The ribbon cable can run through a hole into the center. I'm planning to make this pillar part of a half-length case lid that will sit up front.

I want to ask a few questions before I get too far, though.

1. What mounting hardware does the TFT come with? The [Amazon page](https://www.amazon.com/BIGTREETECH-Direct-Capacitive-Octoprint-Raspberry/dp/B08F1WMQ1J) shows brass standoffs and mentions M2.5 screws but doesn't list what hardware comes it ships with.
2. Will the screen look okay without an outer protective panel?

Thanks!

**Comment by Majawat** [comment]
Lovely! I got the 5" last week and attached it just to get KlipperScreen working to play with. 

1. No other hardware. Just the standoffs, screws, screen, and short cable. 
2. I think so! There's a small bezel around the screen otherwise no features. 
![16582480041882233247007454571949](https://user-images.githubusercontent.com/12058855/179801454-594825cf-4b07-4c83-bfa1-99a6b26ca6e3.jpg)
![16582480263618100400720920912990](https://user-images.githubusercontent.com/12058855/179801506-f398235a-71a8-4d7e-8c18-e21317f4020d.jpg)
![16582480622098561601576929243596](https://user-images.githubusercontent.com/12058855/179801624-2fc40eac-4c00-4536-8ada-9a9b5443b3e6.jpg)
(Forgive the mess)

There is a small potential clearance issue with the display cable on the left. Or the brightness dial on the top right. 

Let me know if you need any other info

**Comment by jon-harper** [comment]
Thanks a ton for the pics! Unexpected and super helpful!

Can you tell me how long those standoffs and screws are? I'm probably going to hijack them to help mount the screen, rather than using the outer screw holes.

**Comment by Majawat** [comment]
![16582488184391460265272870640024](https://user-images.githubusercontent.com/12058855/179803999-4a10f81b-19f1-47ba-b538-27bd8f95ae89.jpg)
![16582488459179158515220938441362](https://user-images.githubusercontent.com/12058855/179804102-5a340bfc-d219-432e-b061-d8ad4481b5e6.jpg)

**Comment by jon-harper** [comment]
[PiTFT Test 1.zip](https://github.com/jon-harper/OmniBox/files/9173872/PiTFT.Test.1.zip)

This is a test for fit file. If it works, the rest of the mount should work and I'll send you a full STL for the lid/stand combo.

Steps:

- Add the standoffs to the TFT in the Raspberry Pi holes;
- The standoffs should fall in to the holes in the tray;
- You should be able to use the stock 2.5mm screws to then tighten it.

If anything doesn't go as planned, lemme know! I guessed at the size of the holes for the standoffs. Right now they're 6.5mm, which should be loose enough. If they could be tighter or don't fit at all, likewise let me know. 

Thanks again for testing this!

**Comment by Majawat** [comment]
Seems pretty perfect. 

![16585889359862070284296899516477](https://user-images.githubusercontent.com/12058855/180610891-9deee0a0-0da1-4dcb-9bbe-9a16e4e23414.jpg)


I looked at the standoff holes, they're slightly big, but it's stable without needing to be tighter.

**Comment by jon-harper** [comment]
[Lid - PITFT.zip](https://github.com/jon-harper/OmniBox/files/9174036/Lid.-.PITFT.zip)

Awesome! Here's the TFT mount, then. This is a half lid so that you can customize the back half still. I haven't uploaded that template yet but will soon.

I hope I got the slot for the flat ribbon cable in the right orientation.

**Comment by Majawat** [comment]
I think I'm a bit confused. Where is this supposed to go on the box? Up top like this?

![16586146464841790481190726402582](https://user-images.githubusercontent.com/12058855/180624702-0e3799d8-90b6-4bf4-b1ac-e27c384d80b4.jpg)


I was thinking it would have gone in the front, like here instead:
![1658614671791747118978644729123](https://user-images.githubusercontent.com/12058855/180624719-b0d6e854-c036-432a-bdb9-0a0b64725192.jpg)

**Comment by Majawat** [comment]
![16586159111923008856713443708141](https://user-images.githubusercontent.com/12058855/180625171-08f0fd9e-693c-41df-a0a1-7293e5b219dd.jpg)
Also, it would probably be better if the cable came in through the side instead of the top if possible.

**Comment by jon-harper** [comment]
> I think I'm a bit confused. Where is this supposed to go on the box? Up top like this?

Yes indeed. This is the format for the Pi TFT that Steve's case uses, and I admit I took the placement from him. The normal printer display goes below so that they appear stacked at an angle with the Pi TFT above.

Quick render:

![Case Master - OmniBox v64](https://user-images.githubusercontent.com/11852387/180633965-e08edd8a-0440-47de-9124-23be6d524f8a.png)

> I was thinking it would have gone in the front, like here instead: 

The 12864 or other LCD screen usually goes there. Are you planning to do entirely without? I can adapt the Pi TFT stand for the front easily enough, though I do still need to get the top version finished.

> Also, it would probably be better if the cable came in through the side instead of the top if possible.

Gotcha. I'll add a side cutout for the wire. Do you ever use the top cable port or any wiring on the other sides? Any issues with cable reach?

---

0.9.7 is almost packed up for release. When it's done today I'm going to create the 0.9.8 branch to add this and the MOSFET mount.

FYI, I also have a half-size lid to add that will go behind the Pi TFT screen and cover the back half of your case (with a handle, too).

**Comment by Majawat** [comment]
> The 12864 or other LCD screen usually goes there. Are you planning to do entirely without?

Yep! I'm running Klipper on my RPI for an Ender 5 Plus. None of which supports the original screen without heavy software modifications (a different Klipper fork). So I'll only be using the PITFT. 

I see no issues with the top print, so I'd call that one good!

(Sorry for the close/reopening, my finger slipped as I typed)

**Comment by jon-harper** [comment]
Awesome! I'll go ahead and commit the Pi TFT lid, but I'll leave this issue open. It shouldn't take too much time to attach the modify a display template now that the fit work is done. I'll plan to have that to you (sometime =) this week.

**Comment by jon-harper** [comment]
Howdy Majawat. Hopefully this works and is what you were looking for.
