### ISSUE TITLE
Ender 5 Plus MOSFET tray

### ISSUE THREAD

**Issue by Majawat** [jon-harper/OmniBox#6]
The Ender 5 Plus has a bed heater MOSFET that I'd like to mount inside the OmniBox of course.

It seems to be a Creality specific part. But fortunately someone on Printables created a mount that includes the Octopus which might help getting the mount hole pattern: https://www.printables.com/model/171559-ender-5-plus-btt-octopus-mosfet-mounting-adapter

**Comment by jon-harper** [comment]
[Lower Bay Tray - Creality MOSFET v1.zip](https://github.com/jon-harper/OmniBox/files/9147604/Lower.Bay.Tray.-.Creality.MOSFET.v1.zip)

Your link included a Fusion file. 👍

Let me know if the clearance is sufficient and the mounting holes deep enough. Or any other issues, of course. 🙂

**Comment by Majawat** [comment]
![16588584579475352345494484145221](https://user-images.githubusercontent.com/12058855/181078617-7cddd027-b902-4f66-993f-7cb1652757ab.jpg)

Looks good to me

**Comment by jon-harper** [comment]
Awesome! ✔
