### ISSUE TITLE
[MCU Tray] MKS Skipr 

### ISSUE THREAD

**Issue by Killajoedotcom** [jon-harper/OmniBox#70]
### UNTESTED. My submission for the MKS Skipr

Wanted to use a spare MKS Skipr motherboard but noticed only BTT stuff was supported. Generated this version for myself, but wanted to give back to the project because it's so good. I have yet to print and test this, but it uses M3 heatserts for longevity. 

![Screenshot 2022-11-25 044527](https://user-images.githubusercontent.com/53958186/203966532-7db53073-5631-44fc-8fec-4811adcd81a2.jpg)
[MCU Tray - MKS Skipr - Heatserts.zip](https://github.com/jon-harper/OmniBox/files/10091813/MCU.Tray.-.MKS.Skipr.-.Heatserts.zip)

If good enough, I hope this can be added to the project eventually.

**Comment by jon-harper** [comment]
Thanks!

I made a note on the PR that I totally messed it up. I've cherry-picked the files into `-unstable` and will fix up a version with stock screw holes, too.

Let me know how the fit test goes; once I've done my end and the fit test is okay I'll close this.

**Comment by jon-harper** [comment]
Your tray looks great! I believe your design is for the 4mm long inserts? They're much more common than the ones I use in the rest of the case so I kept your design and added one for the 5.7mm long inserts and one without inserts at all (like standard trays).

**Comment by Killajoedotcom** [comment]
> 

Yes, I build Vorons quite frequently and have hundreds of the M3x5x4 heatserts on hand. Thanks for making other versions.

**Comment by jon-harper** [comment]
> Yes, I build Vorons quite frequently and have hundreds of the M3x5x4 heatserts on hand. 

This...is something I very much should consider moving forward.

> Thanks for making other versions.

Thanks for suggesting the board *and* making the first one!

**Comment by jon-harper** [comment]
Got this in the docs now. Closing.
