### ISSUE TITLE
MakerBase MKS Monster8 support

### ISSUE THREAD

**Issue by jon-harper** [jon-harper/OmniBox#74]
This is a placeholder issue until a fit test is completed.

**Comment by 3D-Experiments** [comment]
![Monster8-v2 3](https://github.com/user-attachments/assets/37e466f4-5216-4c59-8a35-f91d6da4ac11)

Fits on carrier with heat set inserts installed. I will try fitting carrier board into case once I'm done printing the rest.

**Comment by jon-harper** [comment]
Thanks!
