### ISSUE TITLE
MCU Tray - Fysetc Spider

### ISSUE THREAD

**Issue by MaffooClock** [jon-harper/OmniBox#87]
I've used the template to design a MCU tray for the [Fysetc Spider](https://wiki.fysetc.com/Spider/).

![MCU Tray - Fysetc Spider](https://user-images.githubusercontent.com/540782/211206517-61292065-4763-4c77-88eb-418d8ac42add.png)

I've opened PR #86 for you to review and consider.

**Comment by jon-harper** [comment]
Thanks! Have you had a chance to fit test yet?

**Comment by MaffooClock** [comment]
I have not, but I am printing it at this very moment, and will share a photo of the MCU mounted and the tray inside the body.

**Comment by jon-harper** [comment]
Rock on, thanks!

**Comment by MaffooClock** [comment]
Wahoo, it works!  Even though I haven't finished assembling my OmniBox, I don't see any clearance or wiring issues at this point.

![IMG_4269](https://user-images.githubusercontent.com/540782/211220190-3a3c7d6f-10c9-4671-a17a-42a678706705.JPG)
![IMG_4270](https://user-images.githubusercontent.com/540782/211220195-4271f2c3-c4cc-43c5-8f0f-b0f83f43199f.JPG)

**Comment by jon-harper** [comment]
Sweet! I'll get this merged and in the docs; leaving it open for now (so I don't forget). Thanks for the design!

**Comment by jon-harper** [comment]
It's in the docs. Closing.
