### ISSUE TITLE
Display template is faulty

### ISSUE THREAD

**Issue by jon-harper** [jon-harper/OmniBox#91]
A user reported that the display template has the wrong mounting hole locations. The template is inherited from Steve's project, so it very well may never have been updated.

**Comment by MaffooClock** [comment]
I used this template for my BTT Pi TFT50 display (#88), and while those components fit together perfectly, I did notice the mounting holes in the corners were slightly off from those in the main body; ~1-2mm vertically inward (horizontal spacing lines up fine).

I started to bring this up, but figured it might be possible that my main body component warped slightly during printing, so I didn't want to say anything until I was certain.  I wanted to check the design file for the main body to see what the vertical distance is between mounting holes to compare with those in the template (and my designed based off that), but I don't see a .f3d or .step file.

I'll hold off on submitting a PR #88 until we can confirm correct spacing.

**Comment by jon-harper** [comment]
Thank you for checking on this; there are a couple of entangled display bugs/requests here I need to sort out. I intend to pare down the bug list later this week, hopefully knock this one out, and get some new stuff merged. :smile:

**Comment by MaffooClock** [comment]
Now that you got this sorted out, what is the vertical distance between screw holes supposed to be?  As a test, I re-printed my BTT Pi TFT50 with 103mm vertical distance, and it was spot-on (horizontal distance was unchanged).

I'll submit a PR for the new display panel once I know the correct measurement 👍

**Comment by jon-harper** [comment]
103.825mm 😊
